language: python
sudo: required
cache: pip
dist: trusty

matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: PYVER=py27
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: PYVER=py36

install:
  - ./.ci/travis/install.sh

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - ./.ci/travis/run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
