#!/usr/bin/env python3

import argparse
import sys
import os
import yaml
import subprocess


def subprocess_run(*popenargs, input=None, check=False, **kwargs):
    if input is not None:
        if 'stdin' in kwargs:
            raise ValueError('stdin and input arguments may not both be used.')
        kwargs['stdin'] = subprocess.PIPE

    process = subprocess.Popen(*popenargs, **kwargs)
    try:
        stdout, stderr = process.communicate(input)
    except:
        process.kill()
        process.wait()
        raise
    retcode = process.poll()
    if check and retcode:
        raise subprocess.CalledProcessError(
            retcode, process.args, output=stdout, stderr=stderr)
    return retcode, stdout, stder
 

root_sources = os.environ['ROOTSOURCES']
print("ROOT sources: ", root_sources)
pkg_path = os.environ['ROOT_PKG_PATH']
print("ROOT packages installation path: ", pkg_path)
pwd_path = os.getcwd()
print("root-get location: ", pwd_path)

os.chdir(pwd_path)
path = pwd_path + "/withdep.py"
file = "> math.yml"
command = ['python3'] + [path] + [root_sources, 'math'] + [file]
 
f = open("math.yml", "w")

subprocess.run(command, stdout=f)

try:
    completed = subprocess.run(command, stdout=f)
#    exit(completed.returncode)
except: # Lower than python3.5
    completed = subprocess.run(command, stdout=f)
#    exit(completed[0])
 
db_source = open("math.yml", "r")
db_source = str(db_source)
# path: math/quadp/
#"""
db_manifest = yaml.load(db_source)
print(db_manifest)
 
#os.remove('math.yml')

for pkg in db_manifest:
  if "deps" in db_manifest[pkg].keys():
    if type(db_manifest[pkg]["deps"]) == str:
      db_manifest[pkg]["deps"] = [db_manifest[pkg]["deps"]]
  else:
    db_manifest[pkg]["deps"] = []
  db_manifest[pkg]["installed"] = os.path.isdir(os.path.join(pkg_path, pkg))

print(db_manifest)

def install_pkg(pkg):
  if pkg not in db_manifest.keys():
    print("Can't find package " + pkg)
    return False

  if db_manifest[pkg]["installed"] == True:
    return True

  for dep in db_manifest[pkg]["deps"]:
    if not install_pkg(dep):
      return False
  print("Installing " + pkg)
  src_dir = db_manifest[pkg]["path"]
  full_src_dir =root_sources + "/" + src_dir
  ec = os.system(pwd_path + "/" + "build-pkg " + pkg + " " + full_src_dir)
  if ec != 0:
    print("Failed to install package")
    return False
  db_manifest[pkg]["installed"] = True
  return True

def do_install(args):
  if not install_pkg(args[0]):
    exit(1)
  pass

def do_list(args):
  for pkg in list(db_manifest.keys()):
    print(pkg)
  pass

def do_search(args):
  print(args)
  pass

actions = {
  "-i" : do_install,
  "--install" : do_install,
  "-l" : do_list,
  "--list" : do_list,
}

if sys.argv[1] in actions.keys():
  actions[sys.argv[1]](sys.argv[2:])
else:
  actions["-i"](sys.argv[1:])

exit(0)
manifest = None

with open(sys.argv[1], 'r') as stream:
  try:
    manifest = yaml.load(stream)
  except yaml.YAMLError as exc:
    print(exc)
